"""empty message

Revision ID: 231dcdfcb967
Revises: 9b324e00578e
Create Date: 2024-11-14 14:49:51.757272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '231dcdfcb967'
down_revision = '9b324e00578e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.drop_column('genres')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
