"""empty message

Revision ID: 718431f4fcda
Revises: e4b626127ead
Create Date: 2024-11-14 03:14:49.097939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '718431f4fcda'
down_revision = 'e4b626127ead'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genres', sa.ARRAY(sa.String(length=120)), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.drop_column('genres')

    # ### end Alembic commands ###
